# Generated by Django 4.2.1 on 2023-06-11 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TechnoStyleApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Curso",
        ),
    ]
