# Generated by Django 4.2.1 on 2023-06-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("TechnoStyleApp", "0002_delete_curso"),
    ]

    operations = [
        migrations.CreateModel(
            name="articulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=20)),
                ("modelo", models.CharField(max_length=20)),
                ("categoria", models.CharField(max_length=20)),
                ("precio", models.IntegerField()),
            ],
        ),
    ]
