# Generated by Django 4.2.1 on 2023-06-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TechnoStyleApp", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="clientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("dni", models.IntegerField()),
                ("correo", models.CharField(max_length=20)),
                ("telefono", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="sucursales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("numero_sucursal", models.IntegerField()),
                ("direccion", models.CharField(max_length=50)),
            ],
        ),
    ]
