# Generated by Django 4.2.1 on 2023-07-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TechnoStyleApp", "0005_articulo_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=40)),
                ("descripcion", models.TextField(max_length=1000)),
            ],
        ),
    ]
