# Generated by Django 4.2.1 on 2023-07-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TechnoStyleApp", "0006_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
